Not fork child process on installing recursive packages. Install dependencies package first. Add "reinstall" command for re-install dependencies tree. Change update option for default use cached setup.ini. Add "--update" option and "-u" changed for update setup.ini from mirror.

diff --git a/apt-cyg b/apt-cyg
--- a/apt-cyg
+++ b/apt-cyg
@@ -1,19 +1,19 @@
 #!/bin/bash
 
 # apt-cyg: install tool for cygwin similar to debian apt-get
-#
+# 
 # Copyright (C) 2005-9, Stephen Jungels
-#
+# 
 # This program is free software; you can redistribute it and/or
 # modify it under the terms of the GNU General Public License
 # as published by the Free Software Foundation; either version 2
 # of the License, or (at your option) any later version.
-#
+# 
 # This program is distributed in the hope that it will be useful,
 # but WITHOUT ANY WARRANTY; without even the implied warranty of
 # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 # GNU General Public License for more details.
-#
+# 
 # (http://www.fsf.org/licensing/licenses/gpl.html)
 
 # this script requires some packages
@@ -34,6 +34,7 @@ function usage()
 {
   echo apt-cyg: Installs and removes Cygwin packages.
   echo "  \"apt-cyg install <package names>\" to install packages"
+  echo "  \"apt-cyg reinstall <package names>\" to re-install packages"
   echo "  \"apt-cyg remove <package names>\" to remove packages"
   echo "  \"apt-cyg update\" to update setup.ini"
   echo "  \"apt-cyg show\" to show installed packages"
@@ -45,7 +46,8 @@ function usage()
   echo "  --mirror, -m <url> : set mirror"
   echo "  --cache, -c <dir>  : set cache"
   echo "  --file, -f <file>  : read package names from file"
-  echo "  --noupdate, -u     : don't update setup.ini from mirror"
+  echo "  --update, -u       : force update setup.ini from mirror"
+  echo "  --noupdate         : don't update setup.ini from mirror (default)"
   echo "  --ignore-case, -i  : Ignore case distinctions in <patterns> when finding packages"
   echo "  --help"
   echo "  --version"
@@ -65,24 +67,24 @@ function version()
 function findworkspace()
 {
   # default working directory and mirror
-
+  
   mirror=ftp://mirror.mcs.anl.gov/pub/cygwin
   cache=/setup
-
+  
   # work wherever setup worked last, if possible
-
+  
   if test -e /etc/setup/last-cache
   then
     tmp="`head -1 /etc/setup/last-cache`"
     cache="`cygpath -au "$tmp"`"
   fi
-
+  
   if test -e /etc/setup/last-mirror
   then
     mirror="`head -1 /etc/setup/last-mirror`"
   fi
   mirrordir="`echo "$mirror" | sed -e "s/:/%3a/g" -e "s:/:%2f:g"`"
-
+  
   echo Working directory is $cache
   echo Mirror is $mirror
   mkdir -p "$cache/$mirrordir"
@@ -90,7 +92,7 @@ function findworkspace()
 }
 
 
-function getsetup()
+function getsetup() 
 {
   if test "$noscripts" == "0" -a "$noupdate" == "0"
   then
@@ -126,16 +128,130 @@ function checkpackages()
 }
 
 
+function install_package_noscripts()
+{
+  checkpackages >/dev/null
+  findworkspace >/dev/null
+  local pkg=$1
+  
+  ignore_recursive_packages=${ignore_recursive_packages}%${pkg}%
+
+  if test "$command" != "reinstall"
+  then
+    local already=`grep -c "^$pkg " /etc/setup/installed.db`
+    if test $already -ge 1
+    then
+      echo Package $pkg is already installed, skipping
+      return 0
+    fi
+  fi
+  echo ""
+  echo Checking dependencies for $pkg
+
+  # look for package and save desc file
+
+  mkdir -p "release/$pkg"
+  cat setup.ini | awk > "release/$pkg/desc" -v package="$pkg" \
+    'BEGIN{RS="\n\n@ "; FS="\n"} {if ($1 == package) {desc = $0; px++}} \
+     END {if (px == 1 && desc != "") print desc; else print "Package not found"}' 
+  
+  local desc=`cat "release/$pkg/desc"`
+  if test "-$desc-" = "-Package not found-"
+  then
+    echo Package $pkg not found or ambiguous name
+    rm -r "release/$pkg"
+    return 1
+  fi
+  echo Found package $pkg
+
+  # download and unpack the bz2 file
+
+  # pick the latest version, which comes first
+  local install=`cat "release/$pkg/desc" | awk '/^install: / { print $2; exit }'` 
+
+  if test "-$install-" = "--"
+  then
+    echo "Could not find \"install\" in package description: obsolete package?"
+    return 1
+  fi
+  
+  # recursively install required packages
+  
+  echo > /tmp/awk.$$ '/^requires: / {s=gensub("(requires: )?([^ ]+) ?", "\\2 ", "g", $0); print s}'
+  local requires=`cat "release/$pkg/desc" | awk -f /tmp/awk.$$`
+  
+  local warn=0
+  if ! test "-$requires-" = "--"
+  then
+    echo Package $pkg requires the following packages, installing:
+    echo $requires
+    local package
+    for package in $requires
+    do
+      if [ ! `echo ${ignore_recursive_packages} | grep "%${package}%"` ]
+      then 
+        install_package_noscripts $package
+      fi
+      if ! test $? = 0 ; then warn=1; fi
+    done
+  fi
+  if ! test $warn = 0
+  then
+    echo "Warning: some required packages did not install, continuing"
+  fi
+  
+  echo ""
+  echo Installing $pkg
+  checkpackages >/dev/null
+  findworkspace >/dev/null
+
+  local file=`basename $install`
+  cd "release/$pkg"
+  if test "$noupdate" == "0" -a -f "$file"
+  then
+    rm $file
+  fi
+  wget -nc $mirror/$install
+  
+  # check the md5
+  local digest=`cat "desc" | awk '/^install: / { print $4; exit }'` 
+  local digactual=`md5sum $file | awk '{print $1}'`
+  if ! test $digest = $digactual
+  then
+    echo MD5 sum did not match, exiting
+    return 1
+  fi
+  
+  echo "Unpacking..."
+  cat $file | bunzip2 | tar > "/etc/setup/$pkg.lst" xvf - -C /
+  gzip -f "/etc/setup/$pkg.lst"
+  cd ../..
+  
+  
+  # update the package database
+  
+  cat /etc/setup/installed.db | awk > /tmp/awk.$$ -v pkg="$pkg" -v bz=$file \
+    '{if (ins != 1 && pkg < $1) {print pkg " " bz " 0"; ins=1}; print $0} \
+     END{if (ins != 1) print pkg " " bz " 0"}'
+  mv /etc/setup/installed.db /etc/setup/installed.db-save
+  mv /tmp/awk.$$ /etc/setup/installed.db
+  
+  
+  echo Package $pkg installed
+}
+
+
 # process options
 
 noscripts=0
-noupdate=0
+noupdate=1
 file=""
 dofile=0
 nocase=0
 command=""
 filepackages=""
 packages=""
+ignore_recursive_packages=""
 
 function process_args () {
   while test $# -gt 0
@@ -157,8 +273,13 @@ function process_args () {
         shift
       ;;
 
-      --noupdate|-u)
+      --noupdate)
         noupdate=1
+        shift
+      ;;
+
+      --update|-u)
+        noupdate=0
         shift
       ;;
 
@@ -194,7 +315,7 @@ function process_args () {
        shift
      ;;
 
-      update|show|search|find|describe|packageof|install|remove)
+      update|show|search|find|describe|packageof|install|reinstall|remove)
         if test "-$command-" = "--"
         then
           command=$1
@@ -243,6 +364,7 @@ case "$command" in
 
   update)
 
+    noupdate=0
     findworkspace
     getsetup
 
@@ -271,11 +393,11 @@ case "$command" in
       echo ""
       echo Searching for installable packages matching $pkg:
       if [[ "$nocase" -eq "1" ]] ; then
-        cat setup.ini | awk -v query="$pkg" \
+      cat setup.ini | awk -v query="$pkg" \
           'BEGIN{RS="\n\n@ "; FS="\n"; ORS="\n"} {IGNORECASE=1; if ($1 ~ query) {print $1}}'
       else
         cat setup.ini | awk -v query="$pkg" \
-          'BEGIN{RS="\n\n@ "; FS="\n"; ORS="\n"} {if ($1 ~ query) {print $1}}'
+        'BEGIN{RS="\n\n@ "; FS="\n"; ORS="\n"} {if ($1 ~ query) {print $1}}'
       fi
     done
 
@@ -321,175 +443,29 @@ case "$command" in
   ;;
 
 
-  install)
+  install|reinstall)
 
     checkpackages
     findworkspace
     getsetup
 
-    declare -A pkg_lookup
-    declare -A pkg_already_installed
-
-    # sanity check - find our currently installed packages, and resolve all case-insensitive names to their correct ones
-    for pkg in $packages ; do
-      # check for previously installed packages
-      pkg_already_installed[$pkg]="0"
-      pkg_lookup[$pkg]="$pkg"
-
-      # case insensitive search
-      if [[ "$nocase" -eq "1" ]] ; then
-        already=`grep -ic "^$pkg " /etc/setup/installed.db`
-        if test $already -ge 1 ; then
-          # get the proper name for the package
-          proper_name=`grep -i "^$pkg " /etc/setup/installed.db | awk '{ print $1 }'`
-          # set our lookup value
-          pkg_lookup[$pkg]="$proper_name"
-          pkg_already_installed[$pkg]="1"
-        fi
-
-      # case sensitive search
-      else
-        already=`grep -c "^$pkg " /etc/setup/installed.db`
-      fi
-
-      if test $already -ge 1 ; then
-        pkg_already_installed[$pkg]="1"
-        continue
-      fi
-
-      # check for new packages and find their proper names
-      if [[ "$nocase" -eq "1" ]] ; then
-        proper_name=`cat setup.ini | awk -v package="$pkg" \
-          'BEGIN{IGNORECASE=1; RS="\n\n@ "; FS="\n"} { if ($1 == package) { propername = $1 ; desc = $0; px++ } } \
-           END {if (px == 1 && desc != "") { print propername ; exit 0 } else { print "Package not found" ; exit 1 } }'`
-        if [[ "$?" != "0" ]] ; then
-          echo "Could not find $pkg, aborting..."
-          exit
-        else
-          echo proper name of $pkg is: $proper_name
-          pkg_lookup[$pkg]="$proper_name"
-          continue
-        fi
-      fi
-    done
-
     for pkg in $packages
     do
-    if [[ ${pkg_already_installed[$pkg]} -eq 1 ]] ; then
-      echo "Package $pkg is already installed, skipping"
-      continue
-    fi
-
-    echo Installing $pkg as ${pkg_lookup[$pkg]}...
-    user_pkg_name="$pkg"
-    pkg="${pkg_lookup[$pkg]}"
-
-    echo ""
-    echo Installing $pkg
-
-    # look for package and save desc file
-
-    mkdir -p "release/$pkg"
-    cat setup.ini | awk > "release/$pkg/desc" -v package="$pkg" \
-      'BEGIN{RS="\n\n@ "; FS="\n"} {if ($1 == package) {desc = $0; px++}} \
-       END {if (px == 1 && desc != "") print desc; else print "Package not found"}'
-
-    desc=`cat "release/$pkg/desc"`
-    if test "-$desc-" = "-Package not found-"
-    then
-      echo Package $pkg not found or ambiguous name, exiting
-      rm -r "release/$pkg"
-      exit 1
-    fi
-    echo Found package $pkg
-
-    # download and unpack the bz2 file
-
-    # pick the latest version, which comes first
-    install=`cat "release/$pkg/desc" | awk '/^install: / { print $2; exit }'`
-    category=`cat "release/$pkg/desc" | awk '/^category: / { print $2; exit }'`
-    requires=`cat "release/$pkg/desc" | awk '/^requires: / { print $2; exit }'`
-
-    if test "-$install-" = "--"
-    then
-      if [[ "$category" == "_obsolete" && ! -z "$requires" ]] ; then
-        echo "$pkg is obsolete and replaced by: $requires"
-      else
-        echo "Could not find \"install\" in package description: obsolete package?"
+      install_package_noscripts $pkg
+      
+      # run all postinstall scripts
+      
+      pis=`ls /etc/postinstall/*.sh 2>/dev/null | wc -l`
+      if test $pis -gt 0 && ! test $noscripts -eq 1
+      then
+        echo Running postinstall scripts
+        for script in /etc/postinstall/*.sh
+        do
+          $script
+          mv $script $script.done
+        done
       fi
-      exit 1
-    fi
-
-    file=`basename $install`
-    cd "release/$pkg"
-    wget -nc $mirror/$install
-
-    # check the md5
-    digest=`cat "desc" | awk '/^install: / { print $4; exit }'`
-    digactual=`md5sum $file | awk '{print $1}'`
-    if ! test $digest = $digactual
-    then
-      echo MD5 sum did not match, exiting
-      exit 1
-    fi
-
-    echo "Unpacking..."
-    cat $file | bunzip2 | tar > "/etc/setup/$pkg.lst" xvf - -C /
-    gzip -f "/etc/setup/$pkg.lst"
-    cd ../..
-
-
-    # update the package database
-
-    cat /etc/setup/installed.db | awk > /tmp/awk.$$ -v pkg="$pkg" -v bz=$file \
-      '{if (ins != 1 && pkg < $1) {print pkg " " bz " 0"; ins=1}; print $0} \
-       END{if (ins != 1) print pkg " " bz " 0"}'
-    mv /etc/setup/installed.db /etc/setup/installed.db-save
-    mv /tmp/awk.$$ /etc/setup/installed.db
-
-
-    # recursively install required packages
-
-    echo > /tmp/awk.$$ '/^requires: / {s=gensub("(requires: )?([^ ]+) ?", "\\2 ", "g", $0); print s}'
-    requires=`cat "release/$pkg/desc" | awk -f /tmp/awk.$$`
-
-    warn=0
-    if ! test "-$requires-" = "--"
-    then
-      echo Package $pkg requires the following packages, installing:
-      echo $requires
-      for package in $requires
-      do
-        already=`grep -c "^$package " /etc/setup/installed.db`
-        if test $already -ge 1
-        then
-          echo Package $package is already installed, skipping
-          continue
-        fi
-        apt-cyg --noscripts install $package
-        if ! test $? = 0 ; then warn=1; fi
-      done
-    fi
-    if ! test $warn = 0
-    then
-      echo "Warning: some required packages did not install, continuing"
-    fi
-
-    # run all postinstall scripts
-
-    pis=`ls /etc/postinstall/*.sh 2>/dev/null | wc -l`
-    if test $pis -gt 0 && ! test $noscripts -eq 1
-    then
-      echo Running postinstall scripts
-      for script in /etc/postinstall/*.sh
-      do
-        $script
-        mv $script $script.done
-      done
-    fi
-
-    echo Package $pkg installed
-
+      
     done
 
   ;;
